import React from "react";

const certifications = [
  'Speaker at the 7th Research Conference of UNEXPO. Title: "Study of the Cycle of Magnetic Hysteresis and Resonance Phenomenon in RLC circuit using Proteus simulator". Puerto Ordaz, Bolivar State. Year 2009.',
  'Speaker at the XII Conference of Research of UNEXPO. Title: "Electro-thermal simulation to detect and identify defects along polymer insulators in the 400 kV Tablazo-Cuatricentenario transmission line". Puerto Ordaz, Bolivar State. Year 2014',
  "Invitation as a speaker for a Conference in UNEXPO. Title: “BLOCKCHAIN”. Puerto Ordaz, Bolivar State. Year 2018",
  'Speaker at the LX ASOVAC Annual Convention. Title: "Theoretical and Experimental Study of the Magnetic Field Generated by a Model of High Voltage Electrical Lines". Bolivar City, Bolivar State. Year 2010',
  'Speaker at the LXI ASOVAC Annual Convention. Title: "Application in the laboratory of the mitigation of the magnetic field through a loop near the high voltage lines". Maracay, State of Aragua. Year 2011',
  'Speaker at the V Ibero-American Congress of Electrical Engineering Students CIBELEC. Title: "Reduction of magnetic fields in high voltage lines using a passive loop". Mérida, State of Mérida. Year 2012',
  'Speaker at the XIII Congress of Engineering Students of the IEEE. Title: "Analysis of the electromagnetic fields of the transmission line configurations associated with the Venezuelan National Electrical System". Maracay, State of Aragua. Year 2012. This work was awarded the 3rd place of the technological fair Wilmar Pérez',
  'Speaker at XII International Congress of Numerical Methods in Engineering and Applied Sciences CIMENICS. Title: "Simulation of electro-thermal behavior in chains of glass and polymer insulators in the presence of saline contamination." City of Pampatar, Margarita Island. Year 2014',
  'Published in the	Memories of the XII International Congress of Numerical Methods in Engineering and Applied Sciences CIMENICS. Title: "Simulation of the electro-thermal behavior in chains of glass and polymer insulators before salt contamination." ISBN: 978-980-7161-04-6. Venezuelan Society of Numerical Methods in Engineering (SVMNI) 2014. Universidad Central de Venezuela',
];

const Awards = () => {
  const awardsList = certifications.map((cert, index) => (
    <li key={index}>
      <span className="fa-li">
        <i className="fas fa-trophy text-warning"></i>
      </span>
      {cert}
    </li>
  ));
  return (
    <div>
      <section className="resume-section" id="awards">
        <div className="resume-section-content">
          <h2 className="mb-5">Awards & Certifications</h2>
          <ul className="fa-ul mb-0">{awardsList}</ul>
        </div>
      </section>
      <hr className="m-0" />
    </div>
  );
};

export default Awards;
